In [ ]:
# Importing the necessary libraries
import requests
import pandas as pd

# Under the Header tab, select general and copy the first part of the request URL
url = 'https://stats.nba.com/stats/leaguedashplayerstats?'

# Header tab, under “Request Headers” subsection
header = {
"Accept" : "application/json, text/plain, */*",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en-US,en;q=0.9",
"Connection": "keep-alive",
"Host": "stats.nba.com",
"Origin": "https://www.nba.com",
"Referer": "https://www.nba.com/",
"Sec-Fetch-Dest": "empty",
"Sec-Fetch-Mode": "cors",
"Sec-Fetch-Site": "same-site",
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36",
"x-nba-stats-origin": "stats",
"x-nba-stats-token": "true"}


#Header Tab, under "Query String Parameter" subsection
params = (
("College", ""),
("Conference", ""),
("Country", ""),
("DateFrom", ""),
("DateTo", ""),
("Division", ""),
("DraftPick", ""),
("DraftYear", ""),
("GameScope", ""),
("GameSegment", ""),
("Height",""),
("LastNGames", "0"),
("LeagueID", "00"),
("Location", ""),
("MeasureType", "Base"),
("Month", "0"),
("OpponentTeamID", "0"),
("Outcome", ""),
("PORound", "0"),
("PaceAdjust", "N"),
("PerMode", "PerGame"),
("Period", "0"),
("PlayerExperience", ""),
("PlayerPosition", ""),
("PlusMinus", "N"),
("Rank", "N"),
("Season", "2021-22"),
("SeasonSegment", ""),
("SeasonType", "Regular Season"),
("ShotClockRange", ""),
("StarterBench", ""),
("TeamID", "0"),
("TwoWay", "0"),
("VsConference", ""),
("VsDivision", ""),
("Weight", ""))

#Using Request library to get the data
response = requests.get(url, headers=header, params=params)
response_json = response.json()
player_stats = pd.DataFrame(response_json['resultSets'][0]['rowSet'])
player_stats.columns = response_json['resultSets'][0]['headers']
player_stats = player_stats.rename(columns={"PLAYER_NAME": "PLAYER"})
player_stats.head()

,PLAYER_ID,PLAYER,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,203932,Aaron Gordon,Aaron,1610612743,DEN,26.0,64,40,24,0.625,...,84,207,90,97,42,107,89,34,5,"203932,1610612743"
1,1630565,Aaron Henry,Aaron,1610612755,PHI,22.0,6,6,0,1.000,...,285,545,549,566,494,582,238,34,5,"1630565,1610612755"
2,1628988,Aaron Holiday,Aaron,1610612756,PHX,25.0,55,29,26,0.527,...,326,342,276,297,355,320,238,34,5,"1628988,1610612756"
3,1630174,Aaron Nesmith,Aaron,1610612738,BOS,22.0,45,27,18,0.600,...,509,399,461,440,208,471,238,34,5,"1630174,1610612738"
4,1630598,Aaron Wiggins,Aaron,1610612760,OKC,23.0,41,10,31,0.244,...,237,205,310,264,522,285,238,34,5,"1630598,1610612760"

In [ ]:
import os
os.getcwd()
from google.colab import drive

drive.mount('/content/gdrive', )
path_to_project = '/content/gdrive/My Drive/Salary Prediction POC/Data' # Enter the path to your folder here
os.chdir(path_to_project)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
UFA = pd.read_csv ('2021_data.csv')
UFA['Player'] = UFA['PLAYER'].astype('str') 
UFA = UFA.rename(columns={"Player": "PLAYER"})
UFA = UFA[UFA['Type'].str.contains('RFA')==False]
UFA = UFA[UFA['Type'].str.contains('nan')==False]
UFA['Type'].value_counts()
UFA.head()

          PLAYER                                     Player_link Type
0  Kawhi Leonard   https://www.spotrac.com/redirect/player/8066/  UFA
2     Chris Paul   https://www.spotrac.com/redirect/player/2609/  UFA
5  Norman Powell  https://www.spotrac.com/redirect/player/17874/  UFA
6     Kyle Lowry   https://www.spotrac.com/redirect/player/2536/  UFA
7  DeMar DeRozan   https://www.spotrac.com/redirect/player/6327/  UFA

In [ ]:
player_stats = player_stats.merge(UFA, on = "PLAYER")
player_stats.head()

,PLAYER_ID,PLAYER,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS,Player_link,Type
0,1627846,Abdel Nader,Abdel,1610612756,PHX,28.0,14,11,3,0.786,...,319,487,278,452,238,34,5,"1627846,1610612756",https://www.spotrac.com/redirect/player/20264/,UFA
1,202692,Alec Burks,Alec,1610612752,NYK,30.0,68,29,39,0.426,...,70,148,181,134,170,34,5,"202692,1610612752",https://www.spotrac.com/redirect/player/8063/,UFA
2,1627936,Alex Caruso,Alex,1610612741,CHI,28.0,31,20,11,0.645,...,103,231,47,139,170,34,5,"1627936,1610612741",https://www.spotrac.com/redirect/player/21076/,UFA
3,203458,Alex Len,Alex,1610612758,SAC,28.0,35,13,22,0.371,...,216,315,458,288,131,34,5,"203458,1610612758",https://www.spotrac.com/redirect/player/13318/,UFA
4,1628035,Alfonzo McKinnie,Alfonzo,1610612741,CHI,29.0,17,8,9,0.471,...,484,433,491,469,238,34,5,"1628035,1610612741",https://www.spotrac.com/redirect/player/24106/,UFA